### ISSUE TITLE
Unhandled Errors

### ISSUE THREAD

**Issue by jdppettit** [silverp1/space-personal#27]
1. When creating a 32-bit Linode on new infra without 32-bit support:

```
[linode.boot] Unable to boot 32-bit on this host.  Please open a support ticket.71.58.54.56 - - [17/Feb/2015 10:23:33] "POST /server/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/space/space.py", line 32, in decorator
    return f(*args, **kwargs)
  File "/srv/space/space.py", line 259, in new_server
    boot_linode(linodeID)
  File "/srv/space/linodefunctions.py", line 99, in boot_linode
    api.linode.boot(LinodeID=linodeID)
  File "/usr/lib/python2.6/site-packages/linode/api.py", line 27, in __call__
    return self.klass._worker_func(self.path, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/linode/api.py", line 76, in _worker_func
    return self._request(api_kwargs)
  File "/usr/lib/python2.6/site-packages/linode/api.py", line 69, in _request
    raise LinodeException(content.get('ACTION'), content.get('ERRORARRAY'))
LinodeException
```

**Comment by levlaz** [comment]
So you still cannot create a 32bit host without intervention. Are we
planning on offering 32 bit in Space? I feel like we should take the
initiative and help push the world to 64 bit? :)

**Comment by jdppettit** [comment]
I don't want to necessarily offer 32 bit, but Linode doesn't do a great job at pointing out what images are 32 bit / 64 bit so I just imported them all and let people pick. I feel like its probably okay to leave 32 bit images in there as long as we tell people it failed. What do you think?

**Comment by levlaz** [comment]
Hm, yeah thats a good point, I will take a look and see if we can jerry
rig something. :)

**Comment by jdppettit** [comment]
I don't want to tell people to open tickets because that is kind of crummy, but in the same breath it isn't easy to figure out what is what. Perhaps that can be fixed? :+1:

**Comment by levlaz** [comment]
I will work my levops magic.

**Comment by jdppettit** [comment]
levops++

**Comment by levlaz** [comment]
The Linode API should tell us if a distro is 64 bit or not. 

https://www.linode.com/api/utility/avail.distributions

""IS64BIT":0," 

If the answer is 0, we should not include these disk images as available options. :)

**Comment by levlaz** [comment]
Im gonna work on this.
